[project]
name = "chatten-app"
dynamic = ["version"]
description = "Application-related code for RAG with sources on Databricks platform"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chatten",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.uv.sources]
chatten = { workspace = true }

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"