[project]
name = "chatten-app"
dynamic = ["version"]
description = "Application-related code for RAG with sources on Databricks platform"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chatten",
    "chatten-ui",
    "dash>=2.18.2",
    "databricks-sdk>=0.43.0",
    "fastapi>=0.115.8",
    "pypdf>=5.2.0",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "rapidfuzz>=3.12.1",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
chatten = { workspace = true }
chatten-ui = { workspace = true }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"
