[project]
name = "chatten-rag"
dynamic = ["version"]
description = "Data extraction and RAG model on Databricks platform"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chatten",
    "databricks-sdk>=0.43.0",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[tool.uv.sources]
chatten = { workspace = true }

[dependency-groups]
dev = [
    "pyspark>=3.5.4",
]

[project.scripts]
loader = "chatten_rag.tasks.loader:Loader.entrypoint"
