[project]
name = "chatten-rag"
dynamic = ["version"]
description = "Data extraction and RAG model on Databricks platform"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chatten",
    "databricks-langchain>=0.3.0",
    "databricks-sdk>=0.43.0",
    "llama-index>=0.12.16",
    "mlflow>=2.20.1",
    "pypdf>=5.2.0",
    "transformers>=4.48.3",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[tool.uv.sources]
chatten = { workspace = true }

[dependency-groups]
dev = [
    "pyspark>=3.5.4",
]

[project.scripts]
loader = "chatten_rag.tasks.loader:Loader.entrypoint"
