[project]
name = "chatten-ui"
dynamic = ["version"]
description = "Custom chat component for Dash"
readme = "README.md"
authors = [{ name = "renardeinside", email = "polarpersonal@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["dash[dev]>=2.18.2", "pyyaml>=6.0.2"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[tool.hatch.build.hooks.custom]
path = "hooks/build.py"

[dependency-groups]
dev = ["hatchling>=1.27.0"]

[tool.hatch.build.targets.wheel]
# we need to explicitly include this folder because it's .gitignore'd
artifacts = ["chatten_ui/**"]
